"""Add exam_code

Revision ID: b3bda21627b9
Revises: d60cd2b5fd24
Create Date: 2026-06-24 00:49:39.165044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b3bda21627b9'
down_revision: Union[str, Sequence[str], None] = 'd60cd2b5fd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_papers_exam_code'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_index(op.f('ix_questions_exam_code'), table_name='questions')
    op.drop_index(op.f('ix_questions_paper_name'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_variants_id'), table_name='question_variants')
    op.drop_index(op.f('ix_question_variants_paper_name'), table_name='question_variants')
    op.drop_table('question_variants')
    op.alter_column('sessions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('question_variants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('paper_name', sa.VARCHAR(), nullable=False),
    sa.Column('original_question_id', sa.INTEGER(), nullable=False),
    sa.Column('triage_profile', sqlite.JSON(), nullable=True),
    sa.Column('variant_text', sa.VARCHAR(), nullable=False),
    sa.Column('variant_options', sqlite.JSON(), nullable=False),
    sa.Column('python_script', sa.VARCHAR(), nullable=True),
    sa.Column('sandbox_answer', sa.VARCHAR(), nullable=True),
    sa.Column('verification_solution', sa.VARCHAR(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_variants_paper_name'), 'question_variants', ['paper_name'], unique=False)
    op.create_index(op.f('ix_question_variants_id'), 'question_variants', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_code', sa.VARCHAR(), nullable=False),
    sa.Column('paper_name', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('question_no', sa.INTEGER(), nullable=False),
    sa.Column('year_and_shift', sa.VARCHAR(), nullable=True),
    sa.Column('question_latex', sa.VARCHAR(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('diagrams', sqlite.JSON(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=True),
    sa.Column('answer', sa.VARCHAR(), nullable=True),
    sa.Column('explanation', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('tag', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('teacher_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_questions_paper_name'), 'questions', ['paper_name'], unique=False)
    op.create_index(op.f('ix_questions_exam_code'), 'questions', ['exam_code'], unique=False)
    op.create_table('exam_papers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_code', sa.VARCHAR(), nullable=False),
    sa.Column('paper_name', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('year_and_shift', sa.VARCHAR(), nullable=False),
    sa.Column('teacher_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_id'), 'exam_papers', ['id'], unique=False)
    op.create_index(op.f('ix_exam_papers_exam_code'), 'exam_papers', ['exam_code'], unique=False)
    # ### end Alembic commands ###
